# Generated by Django 4.2.3 on 2025-04-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "onboarding",
            "0002_courseelement_testelement_videoelement_textelement_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseelement",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="courseelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("video", "Video"),
                    ("test", "Test"),
                    ("task", "Task"),
                ],
                max_length=10,
            ),
        ),
    ]
