# Generated by Django 4.2.3 on 2025-04-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0003_alter_courseelement_title_alter_courseelement_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseelement",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="courseelement",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Текстовый материал"),
                    ("video", "Видеоматериал"),
                    ("test", "Тестовое задание"),
                    ("task", "Практическое задание"),
                ],
                max_length=20,
            ),
        ),
    ]
